spring:
  application:
    name: msuno-server

server:
  port: 8091
 
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 119.29.58.11
  client:
    service-url:
      defaultZone: http://119.29.58.11:8090/eureka
      
    
